[package]
name = "helios"
version = "0.1.3"
edition = "2021"
autobenches = false

[workspace]
members = [
    "cli",
    "client",
    "common",
    "config",
    "types",
    "storage",
    "consensus",
    "execution",
    "forcerelay",
    "test-utils"
]

[dependencies]
client = { path = "./client" }
config = { path = "./config" }
common = { path = "./common" }
types = { path = "./types" }
storage = { path = "./storage" }
consensus = { path = "./consensus" }
execution = { path = "./execution" }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
eyre = "0.6.8"
home = "0.5.4"
ethers = "2.0.7"
env_logger = "0.10.0"
log = "0.4.17"
tracing-test = "0.2.3"
criterion = { version = "0.4", features = [ "async_tokio", "plotters" ]}
plotters = "0.3.3"
tempfile = "3.3.0"
hex = "0.4.3"

[patch.crates-io]
arbitrary = { git = "https://github.com/michaelsproul/arbitrary", rev="f002b99989b561ddce62e4cf2887b0f8860ae991" }

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
