[package]
name = "test-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
ckb-script    = "0.108.0"
ckb-types     = "0.108.0"
ckb-traits    = "0.108.0"
ckb-error     = "0.108.0"
log = "0.4.17"
rand = "0.8.5"
