[package]
name       = "storage"
version    = "0.1.0"
edition    = "2021"
license    = "Apache-2.0"
readme     = "README.md"
keywords   = ["blockchain"]
homepage   = "https://github.com/synapseweb3"
repository = "https://github.com/synapseweb3/forcerelay-verifier"
authors    = ["Boyu Yang <yangby@cryptape.com>"]
rust-version = "1.65"
description  = "The storage part of Forcerelay Verifier"

[dependencies]
types = { path = "../types" }
thiserror = "1.0.37"
rocksdb = { package = "ckb-rocksdb", version ="=0.19.0", default-features = false, features = ["snappy"] }
eth2_types = { git = "https://github.com/synapseweb3/lighthouse", rev = "2c246d6", package = "types" }
# eth_light_client_in_ckb-verification = { version = "0.1.0", git = "https://github.com/synapseweb3/eth-light-client-in-ckb", rev = "054d9ae" }
eth_light_client_in_ckb-verification = { version = "0.2.0-alpha", git = "https://github.com/whfuyn/eth-light-client-in-ckb", rev = "6c2760343a42cd1f6074cd11620291da9467b60e" }