name: Verifier
on:
  pull_request:
    path:
      - .github/workflows/forcerelay-verifier.yaml
      - Cargo.toml
      - Cargo.lock
      - cli/**
      - client/**
      - forcerelay/**
      - src/**
  push:
    branches: forcerelay-sdk
      - .github/workflows/forcerelay-verifier.yaml
      - Cargo.toml
      - Cargo.lock
      - cli/**
      - client/**
      - forcerelay/**
      - src/**

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  forecerelay-test:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: prepare-ckb
        run: |
          if [ ! -f "/tmp/ckb.tar.gz" ]; then
            curl -L https://github.com/nervosnetwork/ckb/releases/download/v0.107.0/ckb_v0.107.0_x86_64-unknown-linux-gnu.tar.gz -o /tmp/ckb.tar.gz
          fi
          tar -zxf /tmp/ckb.tar.gz -C /tmp
          echo "/tmp/ckb_v0.107.0_x86_64-unknown-linux-gnu" >> $GITHUB_PATH
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p forcerelay integration_test -- --ignored
